month 9 step 2
Alexander-Ledyakhov/react-stellar-burger pull request #5
Opened 2024-02-25 12:47 UTC by Alexander-Ledyakhov

2024-02-25 15:23 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/TEn2sULrLFxn2w> - У вас не должно открываться сокет соединение, если пользователь не перешёл на нужную страницу (`/feed`, `/profile/orders`).

- <https://disk.yandex.com/i/RCMmRJZ7PVC-Rw>, <https://disk.yandex.com/i/-HEjpLVMisU7aQ> - у вас не отображаются иконки ингредиентов;

- У вас не отображаются заказы, которые находятся в работе, проверьте ещё раз этот функционал;

- Давайте тут оставим 3 столбика или 2, как это сделано в макете: <https://disk.yandex.com/i/2MiSl5Ua84LQyA>;

- <https://disk.yandex.com/i/59KvCFx5Tkw3OA> - Активной должна быть та ссылка, на которой находится пользователь. А также вы должны использовать компонент `NavLink` из `react-router-dom`, <https://reactrouter.com/en/main/components/nav-link>;

- <https://disk.yandex.com/i/swNvORrYCSGY3A> - В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива. А также вам нужно добавить к этом запросу проверку на истечение `jwt` токена;

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/FWFWtfTEKDF3uQ> - это можно проверить в девтулс, во вкладке `networks`.

- У вас падает приложение:

  - если попытаться открыть `/feed/:id` без авторизации. Этот роут должен быть доступен всем пользователям, а не только авторизованным;
  - если попытаться открыть `/profile/orders/:id` без авторизации. Если пользователь не авторизовался, то его нужно перенаправлять на страницу `/login`;

- Не отображается информация о заказе, если открыть маршрут `feed/:id` в новой вкладке. А также, у вас не должна перезагружаться страница, при закрытии модального окна.

- Вы открываете не тот сокет, вы открываете `norma.nomoreparties.space/api/orders/all`, а вам нужно открывать `norma.nomoreparties.space/api/orders.`

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний (**Надо исправить:**), работа будет принята)**

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +        })
**Надо исправить:**

Запросы лучше делать в `useEffect`,  иначе они будут выполняться каждый рендер компонента, что не есть хорошо.

не совсем понимаю зачем вам проверка на `errorWS`.

if-ы можно объединить, `if(json.success && json.orders.length > 0) { ... }`

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +            return ingredientsItems
**Можно лучше:**

тут можно сразу вернуть `map`.

`return ingredientsID.map(...)`

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +        if (ingredientsID) {
**Надо исправить:**

у вас всё завязано на `ingredientsID` (его кстати, лучше переименовать в `ingredientsIds`). Лучше заранее проверить существует ли он, а уже после создавать другие переменные на его основе.

```js
if(!ingredientsIds.length) return null;

const ingredientsItems = useMemo(() => { ... })
// ...
```

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    const [order, setOrder] = useState('')
**Надо исправить:**

Тут лучше использовать `null`, а не пустую строчку.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    const ingredientsID = order.ingredients
**Надо исправить:**

Тут нужно добавить проверку.

```js
const ingredientsIds = order?.ingredients || []
```

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +                    setOrder(json.orders);
**Надо исправить:**

`order` же вроде должен быть объектом, а не массивом. Разберитесь что же такое `order`, а то тут он у вас массив, а ниже уже объект.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/IconFeed/IconFeed.jsx
> +const IconFeed = ({ingredients}) => {
**Можно лучше:**

в этом компоненте используется всего 2 поля из этого объекта, поэтому лучше передавать их, а не весь объект.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/IconIngredients/IconIngredients.jsx
> +    }
**Надо исправить:**

не стоит выносить jsx в функцию, если там нет какой-то сложной логики. Лучше использовать для этого переменную или компонент. Но старайтесь избегать таких моментов)) 
```jsx
const icon = <img className={styles.iconIngredients_img} src={ingredients.image} alt={`иконка ингридиента "${ingredients.name}"`}/>
```

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/IconIngredients/IconIngredients.jsx
> +            if (index === 5) {
**Можно лучше:**

лучше объединить условие в одно.

`i > 6 && index === 5`

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/IconIngredients/IconIngredients.jsx
> +    const i = allIndex - 6
**Надо исправить:**
 
 Вам не нужна переменная `i`, вам достаточно проверить то что `allIndex > 6`.  Ну и просто `allIndex - 6`, там где вы выводите число

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/IconIngredients/IconIngredients.jsx
> +                {iconIngredients()}
**Надо исправить:**

компонент очень маленький и достаточно простой, лучше не выносить jsx в функции.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/ProfileOrders/ProfileOrders.jsx
> +  }, [dispatch, visible])
**Надо исправить:**

`useEffect` должен идти после всех остальных хуков. А также, тут не нужно добавлять в зависимости `visible`. Т.к. для получения контента модального окна, у вас есть отдельный запрос, который вытаскивает определенный заказ по id.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/ProfileOrders/ProfileOrders.jsx
> +  }, [ordersWS])
**Надо исправить:**

Лучше переименовать `ordersWS` в `profileOrders`

Нужно делать вывод сразу в `jsx`, старайтесь не усложнять логику, там где этого можно избежать))

```jsx
 if(!profileOrders.lenght) return null;

 return (
      <section className={`${styles.profileOrders} custom-scroll custom-scroll-margin`} >
        {profileOrders.map(...)}
      </section>
  )
```

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +        }
**Надо исправить:**

при закрытии модальных окон, страница не должна перезагружаться.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    }, [dispatch])
**Надо исправить:**

Вы должны открывать сокет-соединение только на тех страницах, где оно нужно.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  }, [dispatch, visible])
**Надо исправить:**

Тут не нужен `visible`

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  }, [totalTodayWS])
**Надо исправить:**

Здесь и далее.

Не нужно создать переменную ради переменной.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  }, [ordersWS])
**Надо исправить:**

Старайтесь хранить `jsx` в переменных. Лучше подготовьте массивы данных, а уже после используете их для рендера.

Для фильтрации лучше использовать метод `filter`.

```js
const getOrders = (orders, status) => {
  return orders
    .filter((item) => item.status === status)
    .map((item) => item.number)
    .slice(0, 20);
};

export const FeedPage = ({onClose}) => {
// ...
  const readyOrders =  getOrders(orderWS, "done")
  const pendingOrders = getOrders(orderWS, "pending")
  
  // осталось просто вывести через map
}
```

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  }
**Надо исправить:**

а точно нужно ли так заморачиваться?, почему бы просто не вывести всё что есть в массиве (перед этим обрезав его, показал выше пример)

2024-02-25 15:23 UTC, ArslanMustafin commented on src/services/middleware.js
> +        }
**Надо исправить:**

Мидлвара socketMiddleware должна быть универсальная, в ней не должны быть захардкожены
определенные экшены и адреса, они должны передаваться.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  const done = useMemo(() => {
**Надо исправить:**

здесь и далее.

название переменных должны быть более осмысленные. тут например не просто `done`, а `doneOrders или readyOrders`.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  const list = (status, lengthMin, lengthMax) => {
**Надо исправить:**

не совсем корректно называть массив id ингредиентов `status`. Лучше назвать `ids`.

2024-02-25 15:23 UTC, ArslanMustafin commented on src/page/feed/pageFeed.jsx
> +  const summaryStatus = (status) => {
**Надо исправить:**

не совсем корректно называть массив id ингредиентов `status`. Лучше назвать `ids`. Названии функции также не стоит делать таким. Название функции должно начинаться с глагола.

2024-02-25 21:59 UTC, Alexander-Ledyakhov commented
> https://disk.yandex.com/i/RCMmRJZ7PVC-Rw, https://disk.yandex.com/i/-HEjpLVMisU7aQ - у вас не отображаются иконки ингредиентов;

Здравствуйте, не знаю с чем это связано, кажется не весь проект скачался или залился
Измучался, но так и не понял почему у вас так
Прикрепляю видео с тем, как у меня https://disk.yandex.ru/i/7FwAFYYPFcEd3g

2024-02-25 22:22 UTC, Alexander-Ledyakhov commented
>У вас не отображаются заказы, которые находятся в работе, проверьте ещё раз этот функционал;

Не отображается статус 'created', потому что его бэк не возвращает. 
Статус 'pending' возвращается
На всякий прикрепляю запись https://disk.yandex.ru/i/-tcp0nuXh-h-gg

Также заметил, что при создании заказа бэк возвращает статус 'done'.

Навесил пару проверок допом, но оно не поможет
Было: {(order.status == 'created') && 'Создан'}
Стало: {( (order.status == '') || (order.status == 'created') || ((order.status !== 'done') && (order.status !== 'pending'))) && 'Создан'}

2024-02-25 22:41 UTC, Alexander-Ledyakhov commented
> Давайте тут оставим 3 столбика или 2, как это сделано в макете: https://disk.yandex.com/i/2MiSl5Ua84LQyA;

В макете этого нет, а в задании написано "Реализуйте вёрстку так, чтобы каждая из этих колонок содержала не более 10 записей. Если записей больше — создавайте дополнительную колонку"

Я б там вообще лучше бы скролл навесил и максимум 3 колонки. 
PS. подумал, а почему не сделать так, и сделал

2024-02-26 04:06 UTC, Alexander-Ledyakhov commented on src/components/FeedDetails/FeedDetails.jsx
> +        if (ingredientsID) {
Тут больше не проверка, а ожидание, т.к. ingredientsIds не сразу приходит

С ingredientsID переименовал в ingredientsIds

2024-02-26 04:15 UTC, Alexander-Ledyakhov commented on src/components/FeedDetails/FeedDetails.jsx
> +    const ingredientsID = order.ingredients
Добавил проверку через useEffect, т.к. не понял что обозначает order?.ingredients || [], но обязательно разберусь с этим в свободное время, спасибо

2024-02-26 07:49 UTC, Alexander-Ledyakhov commented on src/page/feed/pageFeed.jsx
> +  }
я б с радостью так сделал

https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#issuecomment-1963086817

2024-02-26 19:45 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Большинство замечаний были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/EZJBKskqxL3PQg> - У вас падает приложение, когда пытаешься зайти на страницу `/profile/orders`, после того как пользователь залогинился.

- <https://disk.yandex.com/i/RCMmRJZ7PVC-Rw> - у вас всё ещё не отображаются иконки ингредиентов. Это связано с z-index. псевдоэлемент `::before` по z-index должен быть меньше, чем иконка ингредиента. <https://disk.yandex.com/i/Wena6QtYPd_O7g>;

- У вас не отображаются заказы, которые находятся в работе, проверьте ещё раз этот функционал;

- Нужно исправить замечания отмеченные в коде. Если у вас возникли какие-то сложности с пониманием кода, то обратитесь к наставнику):
  - <https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501831153>;
  - <https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501837113>;
  - <https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501838874> - нужно убрать эти функции, и вывести всё напрямую в `jsx`, также рекомендую обратиться к наставнику, чтобы он помог вам убрать функцию `summaryStatus`, она явно лишняя. Структуру можно сделать через простой `css`, либо заранее подготовить двумерные массивы для красивого вывода (**без `jsx`**);
  - <https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501839435>;

2024-02-26 19:45 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [dispatch, ordersWS, numberId])
**Надо исправить:**

здесь путанница в `setOrder` уходит объект, хотя выше уходил массив 

```js
 useEffect(() => {
    if (ordersWS) {
        if ( numberId in ordersWS ) {
            getOrderApi(numberId).then((json) => {
                if (json.success) {
                    setOrder(json.orders); // массив
                }
            })
        }
    }
}, [ordersWS, numberId])

useEffect(() => {
  if (numberId && ordersWS) {
    setOrder(ordersWS.find(orderWS => { return orderWS._id === numberId })); // объект или undefined
  }
}, [dispatch, ordersWS, numberId])

```

2024-02-26 19:45 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [order])
**Можно лучше:**

вам не нужен ещё 1 useEffect для того чтобы закинуть ингредиенты в  `ingredientsIds`.

Это можно сделать тут: 

```js
  useEffect(() => {
      if (!numberId || !ordersWS) return;
      
      const selectedOrder = ordersWS.find(orderWS => orderWS._id === numberId); 
      
      if(!selectedOrder) return;
       
      setIngredientsIds(selectedOrder.ingredients);
      setOrder(order);
      
  }, [dispatch, ordersWS, numberId])
```

2024-02-26 19:45 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    const [ingredientsIds, setIngredientsIds] = useState('')
**Надо исправить:**

тут нужно использовать `[]` или `null` а не пустую строку.

2024-02-26 19:45 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [dispatch])
**Надо исправить:**

В этом компоненте не нужно открывать сокет. Сокет должен открываться только на страницах. Для получения нужного заказа у вас есть запрос `getOrderApi(numberId).`.

2024-02-26 19:49 UTC, ArslanMustafin commented
> > У вас не отображаются заказы, которые находятся в работе, проверьте ещё раз этот функционал;
> 
> Не отображается статус 'created', потому что его бэк не возвращает (есть вероятность, что я его просто не успеваю выцепить). Статус 'pending' возвращается На всякий прикрепляю запись https://disk.yandex.ru/i/-tcp0nuXh-h-gg
> 
> Также заметил, что при создании заказа бэк возвращает статус 'done'.
> 
> Навесил пару проверок допом, но оно не поможет Было: {(order.status == 'created') && 'Создан'} Стало: {( (order.status == '') || (order.status == 'created') || ((order.status !== 'done') && (order.status !== 'pending'))) && 'Создан'}

Добрый вечер, не совсем понял ход ваших мыслей, проверку тут не помогут, т.к. ошибка не в них. Ошибка у вас в функции `summaryStatus`. Вы забыли сюда передать `ids` -  https://disk.yandex.com/i/cfAF5iyvynXZ8g

2024-02-26 19:53 UTC, ArslanMustafin commented
> > https://disk.yandex.com/i/RCMmRJZ7PVC-Rw, https://disk.yandex.com/i/-HEjpLVMisU7aQ - у вас не отображаются иконки ингредиентов;
> 
> Здравствуйте, не знаю с чем это связано, кажется не весь проект скачался или залился Измучался, но так и не понял почему у вас так Прикрепляю видео с тем, как у меня https://disk.yandex.ru/i/7FwAFYYPFcEd3g

Связано это с `z-index`, видимо в вашем браузере что-то не учитывается. Рекомендую всё же использовать `Google Chrome` т.к. именно там происходит проверка проекта.

2024-02-27 20:33 UTC, Alexander-Ledyakhov commented on src/components/FeedDetails/FeedDetails.jsx
> +        })
Сделал через useEffect

errorWS убрал

if-ы объединил

---

```
    useEffect(() => {
        if (ordersWS && (numberId in ordersWS)) {
            getOrderApi(numberId).then((json) => {
                if (json.success) {
                    setOrder(json.orders);
                }
            })
        }
    }, [ordersWS, numberId])
  ```

2024-02-27 20:41 UTC, Alexander-Ledyakhov commented on src/page/feed/pageFeed.jsx
> +  }, [totalTodayWS])
Убрал хук
Оставил только totalTodayWS

2024-02-27 21:20 UTC, Alexander-Ledyakhov commented
> ## Code Review
> Здравствуйте!
> 
> Отличная работа.
> 
> ### **Вы молодец!**
> * Большинство замечаний были исправлены;
> 
> ### **Но ещё осталось несколько замечаний, которые нужно исправить:**
> * https://disk.yandex.com/i/EZJBKskqxL3PQg - У вас падает приложение, когда пытаешься зайти на страницу `/profile/orders`, после того как пользователь залогинился.
> * https://disk.yandex.com/i/RCMmRJZ7PVC-Rw - у вас всё ещё не отображаются иконки ингредиентов. Это связано с z-index. псевдоэлемент `::before` по z-index должен быть меньше, чем иконка ингредиента. https://disk.yandex.com/i/Wena6QtYPd_O7g;
> * У вас не отображаются заказы, которые находятся в работе, проверьте ещё раз этот функционал;
> * Нужно исправить замечания отмеченные в коде. Если у вас возникли какие-то сложности с пониманием кода, то обратитесь к наставнику):
>   
>   * [month 9 step 2  #5 (comment)](https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501831153);
>   * [month 9 step 2  #5 (comment)](https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501837113);
>   * [month 9 step 2  #5 (comment)](https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501838874) - нужно убрать эти функции, и вывести всё напрямую в `jsx`, также рекомендую обратиться к наставнику, чтобы он помог вам убрать функцию `summaryStatus`, она явно лишняя. Структуру можно сделать через простой `css`, либо заранее подготовить двумерные массивы для красивого вывода (**без `jsx`**);
>   * [month 9 step 2  #5 (comment)](https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1501839435);

Здравствуйте
1. https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1504944658
2. https://github.com/Alexander-Ledyakhov/react-stellar-burger/pull/5#discussion_r1504956991

2024-02-28 00:16 UTC, Alexander-Ledyakhov commented on src/page/feed/pageFeed.jsx
> +  }, [ordersWS])
>нужно убрать эти функции, и вывести всё напрямую в jsx, также рекомендую обратиться к наставнику, чтобы он помог вам убрать функцию summaryStatus, она явно лишняя. Структуру можно сделать через простой css, либо заранее подготовить двумерные массивы для красивого вывода (без jsx);

Сделал через стили

```
  const getOrders = (orders, statusName) => {
    return orders.filter((item) => item.status === statusName).map((item) => item.number)
  };
  const readyOrders = useMemo(() => ordersWS && getOrders(ordersWS, "done"), [ordersWS])
  const pendingOrders = useMemo(() => ordersWS && getOrders(ordersWS, "pending"), [ordersWS])

```

```
            <div className={`mb-15 ${styles.summary_statuses}`}>
              <div className={styles.summary_status}>
                <h2 className="mb-4 text text_type_main-medium">Готовы:</h2>
                <div className={`${styles.summary_done} ${styles.summary_list}`}>
                  {readyOrders && readyOrders.map((readyOrder) => (
                    <p key={key()} className={`mt-2 mr-2 text text_type_digits-default`}>{readyOrder}</p>
                  ))}
                </div>
              </div>
              <div className={styles.summary_status}>
                <h2 className="mb-4 text text_type_main-medium">В работе:</h2>
                <div className={`${styles.summary_done} ${styles.summary_list}`}>
                  {pendingOrders && pendingOrders.map((pendingOrder) => (
                    <p key={key()} className={`mt-2 mr-2 text text_type_digits-default`}>{pendingOrder}</p>
                  ))}
                </div>
              </div>
            </div>
```

2024-02-28 00:26 UTC, Alexander-Ledyakhov commented on src/services/middleware.js
> +        }
+

2024-02-28 00:53 UTC, Alexander-Ledyakhov commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [dispatch, ordersWS, numberId])
блин кажется getOrderApi возвращает массив до тех пор пока ответ пустой. Почитал про массивы и объекты, там как понял массив это объект в упрощенном виде. 

Я если честно еще думаю, что такое должно правиться на стороне бэка, а на фронте максимум проверять тип того что пришло.

Да и бэк же возвращает всегда данные в виде json-а, а это уже объект

Плюсом, чтоб преобразовать массив в объект нужно знать в каком порядке там данные приходят. Можно конечно наобум собрать объект, но тут кажется можно не заморачиваться так 

----

добавил проверку на тип

```
    useEffect(() => {
        if (ordersWS && (numberId in ordersWS)) {
            getOrderApi(numberId).then((json) => {
                if (json.success) {
                    setOrderApi(json.orders);
                }
            })
            if (orderApi && typeof orderApi == 'object') {
                setOrder(orderApi)
            }
        }
    }, [ordersWS, numberId])
```

---

если тут неверно сделал (соответственно и неверно рассуждал), то прикрепи, пожалуйста, материал про это, чтоб мог почитать и сделать верно

2024-02-28 01:22 UTC, Alexander-Ledyakhov commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [dispatch])
этот запрос не работает, поэтому и сделал через сокет

этот запрос всегда отдает следующее
![Снимок экрана 2024-02-28 041840](https://github.com/Alexander-Ledyakhov/react-stellar-burger/assets/129987745/43d0f529-fea7-42ce-86df-1a36d2255aed)

---

и в задании не сказано про это
![Снимок экрана 2024-02-28 042126](https://github.com/Alexander-Ledyakhov/react-stellar-burger/assets/129987745/261e672f-c780-463e-a771-9dd0153cbcd1)

2024-02-28 01:22 UTC, Alexander-Ledyakhov commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [dispatch])
го скипнем этот коммент

2024-02-28 15:50 UTC, ArslanMustafin commented on src/components/FeedDetails/FeedDetails.jsx
> +    }, [dispatch])
Окей, скипаем, не очень критично))

2024-02-28 20:19 UTC, Alexander-Ledyakhov commented
> > > https://disk.yandex.com/i/RCMmRJZ7PVC-Rw, https://disk.yandex.com/i/-HEjpLVMisU7aQ - у вас не отображаются иконки ингредиентов;
> > 
> > 
> > Здравствуйте, не знаю с чем это связано, кажется не весь проект скачался или залился Измучался, но так и не понял почему у вас так Прикрепляю видео с тем, как у меня https://disk.yandex.ru/i/7FwAFYYPFcEd3g
> 
> Связано это с `z-index`, видимо в вашем браузере что-то не учитывается. Рекомендую всё же использовать `Google Chrome` т.к. именно там происходит проверка проекта.

Оно и в хроме у меня нормально работает((
Попробую пошаманить

2024-02-29 00:50 UTC, Alexander-Ledyakhov commented
Если страница все еще будет падать, скиньте, пожалуйста, полный скрин консольки 
Я кажется поправил, но проблема не воспроизводилась

2024-02-29 09:21 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

2024-02-29 09:21 UTC, ArslanMustafin commented on src/index.js
>  const store = createStore(rootReducer, enhancer);
**Можно лучше:**

Лучше разделить экшены каждого сокет-соединения: 

```js
// пример
const ordersWsActions = {
  wsInit: ORDERS_CONNECTION_INIT,
  wsClose: ORDERS_CONNECTION_CLOSE,
  onOpen: ORDERS_CONNECTION_SUCCESS,
  onClose: ORDERS_CONNECTION_CLOSED,
  onError: ORDERS_CONNECTION_ERROR,
  onMessage: ORDERS_GET_MESSAGE,
};

const feedWsActions = {
  wsInit: FEED_CONNECTION_INIT,
  wsClose: FEED_CONNECTION_CLOSE,
  onOpen: FEED_CONNECTION_SUCCESS,
  onClose: FEED_CONNECTION_CLOSED,
  onError: FEED_CONNECTION_ERROR,
  onMessage: FEED_GET_MESSAGE,
};

const store = createStore(
  rootReducer,
  composeWithDevTools(
    applyMiddleware(
      thunk,
      socketMiddleware(ordersWsActions),
      socketMiddleware(feedWsActions)
    )
  )
);
```

2024-02-29 09:21 UTC, ArslanMustafin commented on src/services/middleware.js
> +
**Можно лучше:**

Немного подскажу, т.к. ваш вариант близок к универсальному. Ранее я говорил про то, что в мидлваре не должны быть захардкожены
определенные экшены и адреса, они должны передаваться, вот как это должно выглядеть: 

```js
export type TwsActions = {
  wsInit: string;
  wsClose: string;
  wsSendMessage?: string;
  onOpen: string;
  onClose: string;
  onError: string;
  onMessage: string;
};

export const socketMiddleware = (
  wsActions: TwsActions
): Middleware<{}, RootState> => {
  return (store) => {
    let socket: WebSocket | null = null;
    const {
      wsInit,
      wsClose,
      wsSendMessage,
      onOpen,
      onClose,
      onError,
      onMessage,
    } = wsActions;

    return (next) => (action) => {
      const { dispatch } = store;
      const { type, payload } = action;

      if (type === wsInit) {
        socket = new WebSocket(payload);
        socket.onopen = (event) => {
          dispatch({ type: onOpen, payload: event });
        };

        socket.onerror = (event) => {
          dispatch({ type: onError, payload: event });
        };

        socket.onmessage = (event) => {
          const { data } = event;
          const parsedData = JSON.parse(data);
          dispatch({
            type: onMessage,
            payload: {
              data: parsedData,
              timestamp: new Date().getTime() / 100,
            },
          });
        };

        socket.onclose = (event) => {
          dispatch({ type: onClose, payload: event });
        };
      }

      if (wsClose && type === wsClose && socket) {
        socket.close();
      }

      if (wsSendMessage && type === wsSendMessage && socket) {
        socket.send(JSON.stringify(payload));
      }

      next(action);
    };
  };
};

// Использование

  useEffect(() => {
    dispatch({
      type: FEED_CONNECTION_INIT,
      payload: BURGER_API_WSS_FEED, // это адрес апишки
    });

    return () => {
      dispatch({ type: FEED_CONNECTION_CLOSE });
    };
  }, [dispatch]);

```

2024-02-29 09:24 UTC, ArslanMustafin commented
> Если страница все еще будет падать, скиньте, пожалуйста, полный скрин консольки Я кажется поправил, но проблема не воспроизводилась

Оказывается это была проблема с моей стороны, у вас врятли такая будет. Дело в том, что в одном из заказов некоторые ингредиенты были `undefined`), поэтому и падала страница. 

https://disk.yandex.com/i/AbTKmwTHMrkCsQ

2024-03-24 00:47 UTC, merged